name: Code Quality Checks

on:
  push:
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies (Frontend)
        working-directory: frontend
        run: npm ci

      - name: Run TypeScript & ESLint (Frontend)
        working-directory: frontend
        run: |
          npx tsc --noEmit
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Install Dependencies (Backend)
        working-directory: backend
        run: npm ci

      - name: Run ESLint & Tests (Backend)
        working-directory: backend
        run: |
          npx eslint . --ext .js,.ts
          npm test
